[project]
name = "nltk-data-abc"
version = "0.1.0.dev1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ryanamannion", email = "ram321@georgetown.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "nltk-data-pack-core",
]

[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"

[tool.uv.sources]
nltk-data-pack-core = { workspace = true }
